"use client";

import Link from "next/link";
import Image from "next/image";
import { useParams } from "next/navigation";
import { experiences } from "@/data/experiences";
import { useFavorites } from "@/components/FavoritesProvider";

export default function DetailPage() { const { id } = useParams<{ id: string }>(); const experience = experiences.find((item) => item.id === id); const { isFavorite, toggleFavorite } = useFavorites(); if (!experience) return <div className="mx-auto max-w-3xl px-5 py-24 text-center"><h1 className="text-3xl font-black">Experience not found</h1><Link href="/experiences" className="mt-5 inline-block font-bold text-teal-700">Back to explore →</Link></div>; return <div className="mx-auto max-w-6xl px-5 py-12"><Link href="/experiences" className="font-semibold text-teal-700">← All experiences</Link><div className="mt-8 grid gap-10 md:grid-cols-2 md:items-center"><div className="relative h-[480px] w-full overflow-hidden rounded-[2.5rem]"><Image src={experience.imageUrl} alt={experience.title} fill sizes="(max-width: 768px) 100vw, 50vw" className="object-cover" /></div><div><p className="text-sm font-bold uppercase tracking-[.2em] text-teal-700">{experience.category} · {experience.destination}</p><h1 className="mt-4 text-4xl font-black tracking-tight text-slate-950 sm:text-5xl">{experience.title}</h1><p className="mt-6 text-lg leading-8 text-slate-600">{experience.description} Join a small group of curious travelers and make a memory that stays with you long after you return home.</p><div className="mt-8 flex gap-8 border-y border-slate-200 py-5"><span><strong className="block text-xl text-slate-950">★ {experience.rating}</strong><small className="text-slate-500">Guest rating</small></span><span><strong className="block text-xl text-slate-950">${experience.price}</strong><small className="text-slate-500">Per person</small></span></div><button onClick={() => toggleFavorite(experience.id)} className="mt-8 rounded-full bg-slate-950 px-6 py-4 font-bold text-white hover:bg-teal-700">{isFavorite(experience.id) ? "♥ Saved to favorites" : "♡ Save to favorites"}</button></div></div></div>; }
